version: '3.8'

services:
  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: libros_api_orm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: libros-api
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:password@database:5432/libros_api_orm"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  pgdata:
